### ISSUE TITLE
Include ldn in SDfiles

### ISSUE THREAD

**Issue by Xebastron** [spacemeowx2/ldn_mitm#1]
Hello, I wanted permission to be able to include in the SDfiles package (https://github.com/AtlasNX/Kosmos/releases), the ldn module. Could do it?

Best regards and thanks :)

**Comment by Cubuss** [comment]
No? ldn isnt even done yet its a WIP,

**Comment by spacemeowx2** [comment]
I think it's time to do it. Now ldn_mitm is more stable and should be able to released.

**Comment by Xebastron** [comment]
Ok, thanks you :)
