### ISSUE TITLE
[Suggestion] Toolbox.json for the ovl_sysmodule tesla plugin

### ISSUE THREAD

**Issue by greensad** [spacemeowx2/ldn_mitm#109]
Would be great if you could include toolbox.json alongside or bundled in your releases so it works out of the box with the tesla plugin ovl_sysmodule. At this point every other major sysmodule now has tesla integration either by simple including a toolbox.json or by converting their homebrew into a tesla plugin. I know the latter is a good chunk of work but the former is a quick and simple fix, having added my own toolbox.json for Idn_mitm just now. Anyway, consider it, would be appreciated!

**Comment by spacemeowx2** [comment]
Any docs?

**Comment by impeeza** [comment]
The file goes on: \atmosphere\contents\4200000000000010\toolbox.json , and the content could be:

```
{
	"name"  : "ldn_mitm",
	"tid"   : "4200000000000010",
	"requires_reboot": true
}
```


It will tell to several sysmodules managers how to enable/disable, start/stop the sysmodule.

**Comment by spacemeowx2** [comment]
The code is ready, but it's not released, check the `sdcard` file.

https://github.com/spacemeowx2/ldn_mitm/actions/runs/1417522631

**Comment by lowburger** [comment]
@spacemeowx2 overlay and toolbox.json is good but pls keep include homebrew nro for user who don't use tesla sysmodule

**Comment by spacemeowx2** [comment]
@lowburger ok, I will add it back before next release

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/ldn_mitm/releases/tag/v1.12.0
