### ISSUE TITLE
Update libnx?

### ISSUE THREAD

**Issue by Skalke** [spacemeowx2/ldn_mitm#11]
May be solve a lot of issues with latest atmo compability

**Comment by designgears** [comment]
Already did
https://github.com/spacemeowx2/ldn_mitm/pull/10

**Comment by Skalke** [comment]
@designgears is it improve stability?

**Comment by designgears** [comment]
I haven't had any kip stability issues with it on atmos 0.8.6, what kind of issues are you running into?

**Comment by Skalke** [comment]
open #5

**Comment by designgears** [comment]
[ldn_mitm.zip](https://github.com/spacemeowx2/ldn_mitm/files/3049931/ldn_mitm.zip)

Try that, it's built using the latest version of libnx.

**Comment by Skalke** [comment]
@designgears this version at least don't conflict with Edizon....i'll do more tests later, if it will be stable, i'll close issues

**Comment by designgears** [comment]
I'd leave the issue open, I'm not a dev on this project, I just needed it updated for my build script so I don't have to install a bunch of different versions of libnx.

**Comment by Skalke** [comment]
updated officially...need to test
