### ISSUE TITLE
Latest Atmosphere

### ISSUE THREAD

**Issue by Glazelf** [spacemeowx2/ldn_mitm#111]
Doesn't seem to connect properly using latest Atmosphere? 
Can anyone confirm or deny this. I'm trying to find where the issue is and I think I've narrowed it down to `ldn_mitm` not working as intended.

Behaviour: acts as if the switch were on another network; connection requests time out.

I assume the solution is updating atmosphere-libs

**Comment by beyondmeat** [comment]
Reddit is reporting the same.

**Comment by FirePow** [comment]
> Reddit is reporting the same.

which redditt sorry im having problems with it too, getting the fatal error that says its not loading or that its too old

**Comment by t0g3pii** [comment]
Im on AMS 1.2.4 with ldn 1.11.0 without any issues.

**Comment by Glazelf** [comment]
Got it to work by reinstalling both `sys-botbase` and `ldn_mitm`.
