### ISSUE TITLE
Firmware 13.2.0 Support

### ISSUE THREAD

**Issue by jobrien97** [spacemeowx2/ldn_mitm#114]
Crashes on Switch boot

**Comment by malSet** [comment]
From my own testing, likely a 13.2.0 issue rather than an Atmosphere 1.2.5 issue, as I was able to boot into my 13.1.0 emunand on AMS 1.2.5 without issue.

**Comment by lowburger** [comment]
Yes, need update for compile with new atmosphere-libs for 13.2.0 fix

**Comment by Glazelf** [comment]
+1, Panic on boot with `ldn_mitm` titleID

**Comment by CaelThunderwing** [comment]
the nightly from 4 hours ago, doesnt panic on boot, nor when toggling on n off.

**Comment by spacemeowx2** [comment]
https://github.com/spacemeowx2/ldn_mitm/releases/tag/v1.12.0
