### ISSUE TITLE
play does not work with new update of the games

### ISSUE THREAD

**Issue by rikimm** [spacemeowx2/ldn_mitm#13]
are running out of several games, so far only smash bros.

**Comment by Cubuss** [comment]
You haven't provided any information, No error log or the setup you are using,

**Comment by rikimm** [comment]
code error  2011-0301

An error has occurred
If the problem is not solved, visit the nintendo support site
url nitendo

**Comment by Cubuss** [comment]
Please update your ldn_mitm to the latest version and try again,

**Comment by spacemeowx2** [comment]
Should be fixed in https://github.com/spacemeowx2/ldn_mitm/commit/ea0dcb607a90921f772a6d2069b43b912db900ee
