### ISSUE TITLE
Pokemon Let's Go Crashes

### ISSUE THREAD

**Issue by Sevyn13** [spacemeowx2/ldn_mitm#15]
In Pokemon Let's Go when selecting local play, then trade, enter in the three pokemon "code" it freezes the game. When I disable ldn_mitm all works as normal.

**Comment by Cubuss** [comment]
Ldn-mitm doesn't work with pokemon lets go cause its using undocumented API,
Here is a list with games that work and dont work:
https://docs.google.com/spreadsheets/d/1Eg_EE0xsBytSyWr7mtvD0MGUjCjyDJBXrHJ8ra8q8-8/edit#gid=0

**Comment by spacemeowx2** [comment]
Closed since it won't fix.

**Comment by dogty** [comment]
By adding the ldn private communicate it seems to have solved the problem with let's go crashing. Can someone confirms it? 

https://github.com/dogty/ldn_mitm/releases (don't pick the beta versions yet)
