### ISSUE TITLE
Which AMS version does the newest idn_mitm, 1.15.0 supported 

### ISSUE THREAD

**Issue by 995387611** [spacemeowx2/ldn_mitm#153]
My system is 16.0.2|1.5.2, it can't be compatible with the 1.14.0. The newest one,1.15.0, is not in the table, can it be compatible.

**Comment by phuongnt175** [comment]
> 

go to release, downlaod 1.15.0 bro

**Comment by spacemeowx2** [comment]
README is updated now.
