### ISSUE TITLE
ldn_mitm is not loaded or too old (requires ldn_mitm >= v1.1.2)

### ISSUE THREAD

**Issue by FabrizioA** [spacemeowx2/ldn_mitm#16]
My NS have 7.0.1 and I have upgrade to Kosmos 12.1.1.
When I open HBMenu I see a ? icon named "ldnmitm cfg" if I click on it I get a black screen with the error "ldn_mitm is not loaded or too old (requires ldn_mitm >= v1.1.2)"
Any suggestion to fix it or remove this icon?
Thank you in advance.

**Comment by FabrizioA** [comment]
![IMG_4013](https://user-images.githubusercontent.com/8628790/57013263-f22cb600-6c0a-11e9-9744-9a0e80029138.jpg)
![IMG_4012](https://user-images.githubusercontent.com/8628790/57013266-f658d380-6c0a-11e9-8e40-16a8742d8c2b.jpg)

**Comment by spacemeowx2** [comment]
You must enable ldn_mitm sysmodule in kosmos toolbox

**Comment by FabrizioA** [comment]
Great! Thank you ;)
