### ISSUE TITLE
PKMN Let's Go Crashes with the latest nightly builds

### ISSUE THREAD

**Issue by Waifu4Life** [spacemeowx2/ldn_mitm#162]
Using Atmosphere version 1.5.4, the latest nightly builds and a legit card of Pokemon Let's Go Eevee trying to connect with Ryujinx LDN playing Let's Go Pikachu in local wireless. After entering the picture password for local play on my Switch, the game crashes a couple of seconds after.

Do I need to configure the first 4 steps on this page http://www.lan-play.com/install even if it's not for LAN play but for wireless play?

Cheers

**Comment by KutaroKazuki** [comment]
> Using Atmosphere version 1.5.4, the latest nightly builds and a legit card of Pokemon Let's Go Eevee trying to connect with Ryujinx LDN playing Let's Go Pikachu in local wireless. After entering the picture password for local play on my Switch, the game crashes a couple of seconds after.
> 
> Do I need to configure the first 4 steps on this page http://www.lan-play.com/install even if it's not for LAN play but for wireless play?
> 
> Cheers

Hello Pokemon Let's Go Series was never supported. This game got always stuck.

**Comment by spacemeowx2** [comment]
#15
