### ISSUE TITLE
LDN Doesn't work at AMS 1.5.4 and 16.0.3

### ISSUE THREAD

**Issue by tomastorm** [spacemeowx2/ldn_mitm#166]
Hello everyone

I have Atmosphere 1.5.4 and console on version 16.0.3, I have installed LDN from the HB Store as a fellow has exactly the same features as me and allows him to play games that require LDN without any issues.

When in any game we try to create a room, we find ourselves without a problem, we can even join, but when the game starts (for example, super smash bros or super mario party) it is when the connection error appears, I attach the .log file so that you can determine what is causing my problem since I have even tried to install the Nightly versions in order to solve this but unfortunately this has continued to happen exactly the same.

I appreciate your possible answers, thank you.

LDN Log:
[ldn_mitm.log](https://github.com/spacemeowx2/ldn_mitm/files/12446624/ldn_mitm.log)

**Comment by Fabelwesen** [comment]
I had the same problem with the same versions. Downgrading Atmosphere to 1.5.3 solved the problem with firmware 16.0.3 and latest nightly of ldn_mitm.

**Comment by tomastorm** [comment]
Don't found for me

**Comment by tomastorm** [comment]
Finally the problem is not the LDN , is the wireless conection.
With ethernet port to usb i solved this.
Thank you to @Fabelwesen to try to help me.
