### ISSUE TITLE
ldn_mitm v1.16.0 crashes with emuNAND official firmware v17.0.0

### ISSUE THREAD

**Issue by johnkelvinliu** [spacemeowx2/ldn_mitm#176]
ldn_mitm v1.16.0 crashes with emuNAND official firmware v17.0.0

It can not load into atmoshpere v1.5.5 after the switch logo with the following error message:
A fatal error has occurred when running Atmosphere.
Title ID: 4200000000000010
Error desc: std::abort() called (0xffe)

Solution:
remove ldn_mitm v1.16.0
microSD card emuNAND: atmosphere\contents\4200000000000010
Delete the whole 4200000000000010 folder
OK to get into atmosphere again.

**Comment by Terry6644** [comment]
same issue, any suggestion now?

**Comment by johnkelvinliu** [comment]
Solution:
remove ldn_mitm v1.16.0
microSD card emuNAND: atmosphere\contents\4200000000000010
Delete the whole 4200000000000010 folder
OK to get into atmosphere again.

**Comment by andrea-ap** [comment]
now i recompiled and  works for 17.0.0 
[ldn-mitm_17.0.0.zip](https://github.com/spacemeowx2/ldn_mitm/files/13193183/ldn-mitm_17.0.0.zip)

**Comment by lowburger** [comment]
@spacemeowx2 need new atmosphere 1.6.2 library and adjust ldn_mitm in socket change https://github.com/switchbrew/libnx/commit/1bb5a21453ebae17b0a5f754c83fbaa98942dc17

**Comment by noxskc** [comment]
Hi
No new version for the firmware v17.0.0 ?

**Comment by PewnyPL** [comment]
Using 4.5.0 (the release source, commits since that break compilation of Atmos libs!) of libnx from https://github.com/switchbrew/libnx Atmosphere-libs in newest version builds properly.
Then, I commented out line 52 of ldnmitm_main.cpp (.bsdsockets_version = 1,) and changed line 71 to .version = 1 (since it was constant anyway).
Now ldn_mitm builds fully, but I have yet to test it on the console (away from home at the moment)

**Comment by PewnyPL** [comment]
Decided to make a new comment. Disregard the last edit in the pervious comment, it WORKS! I just... didn't notice that on Switch I had pokemon version 2.0.2 and in Ryujinx 2.0.1... After updating the game it works.

**Comment by johnkelvinliu** [comment]
We can not even lauch the atmosphere if ldn_mitm v1.16.0 is installed, not to say updating the game.

**Comment by PewnyPL** [comment]
> We can not even lauch the atmosphere if ldn_mitm v1.16.0 is installed, not to say updating the game.

Read my previous comment, I described how I got to build a new version of ldn_mitm that is compatible with new Atmosphere.

**Comment by johnkelvinliu** [comment]
Being a stupid non programmer end user, I don't even know what are you talking about in your previous comment without step by step instruction, sorry.
Could you please update the release here instead?

**Comment by PewnyPL** [comment]
> Being a stupid non programmer end user, I don't even know what are you talking about in your previous comment without step by step instruction, sorry. For example, I have no idea what are Atmos libs, libnx..., etc. Could you please update the release here instead?

I can't make a release here as I don't have permission, but I quickly uploaded it on my github here: https://github.com/PewnyPL/ldn_mitm/releases/tag/17.0.0

**Comment by noxskc** [comment]
Very big Thx @PewnyPL I'll test this as soon as I can ;)

**Comment by impeeza** [comment]
> Using 4.5.0 (the release source, commits since that break compilation of Atmos libs!) of libnx from https://github.com/switchbrew/libnx Atmosphere-libs in newest version builds properly. Then, I commented out line 52 of ldnmitm_main.cpp (.bsdsockets_version = 1,) and changed line 71 to .version = 1 (since it was constant anyway). Now ldn_mitm builds fully, but I have yet to test it on the console (away from home at the moment)
> 
> EDIT: Well, the console boots up without a crash, but it doesn't find Ryujinx-LDN in Pokemon Violet.

This was resolved on Atmosphere-libs today:
https://github.com/Atmosphere-NX/Atmosphere-libs/issues/27

**Comment by MrSolidus89** [comment]
hi, I'm waiting for version 17 please

**Comment by impeeza** [comment]
There is a fork with 17 support:

https://github.com/PewnyPL/ldn_mitm/releases/download/17.0.0/ldn_mitm_17.0.0.zip

on the GBATemp thread: https://gbatemp.net/threads/tesla-the-nintendo-switch-overlay-menu.557362/post-10121629 you can find some interesting links for Overlays and Tesla latest versions.

**Comment by legion5558** [comment]
hello, I copied the files from V17 to the sd card. The 4200000000000010 folder is present in contents and I restarted the switch. I no longer get the error message either. But when I want to create a LAN game in monster hunter generation, I get the following error message: 2110-0106. I must have made a mistake somewhere, but I don't see where.

**Comment by legion5558** [comment]
Ok sorry my wifi was OFF, it's works for me, thank you for the V17

**Comment by johnkelvinliu** [comment]
Does anyone tried the ldn_mitm for v17 atmosphere on v17.0.1 atmosphere?

**Comment by PewnyPL** [comment]
> Does anyone tried the "ldn_mitm for v17.0.0 firmware" on v17.0.1 firmware? Does it works?

It works, nothing changed.

**Comment by Saopanda** [comment]
> > Does anyone tried the "ldn_mitm for v17.0.0 firmware" on v17.0.1 firmware? Does it works?
> 
> It works, nothing changed.

i try a lot of game, no one connect success, just can see room, but joining failed

do you konw any work's well game? i want to try it

**Comment by sousajeferson** [comment]
Oi pessoal, boa noite!

Estou com o erro ao abrir o ldn_mitm 18.1.0-2.
Utilizei a versão acima e mesmo assim não funciona.

**Comment by sousajeferson** [comment]
> Oi pessoal, boa noite!
> 
> Estou com o erro ao abrir o ldn_mitm 18.1.0-2. Utilizei a versão acima e mesmo assim não funciona.

You have to use atmosphere 1.7.1+ for firmware version 18.1.0, update to atmosphere 1.7.1 to use my latest release found here:

https://github.com/DefenderOfHyrule/ldn_mitm/releases/tag/v1.17.0
