### ISSUE TITLE
Bricked Kosmos

### ISSUE THREAD

**Issue by possessedlaptop** [spacemeowx2/ldn_mitm#19]
My nintendo switch seems to be bricked, it doesn't past the Nintendo Switch splash screen.
I toggled on the ldn_mitm on the Hekate Toolbox, asked me to reboot and then it happened.

I'm using the last SDsetup Kosmos package. FW 8.1. Using EmuMMC.

Thanks in advance.

**Comment by Xelaalex1234** [comment]
Same here. I tried deleting everything but the nintendo folder but the problem persists with no leftover configs whatsoever.

**Comment by spacemeowx2** [comment]
If you want to disable ldn_mitm manually, delete the file in SD card: `sdcard://atmosphere/titles/4200000000000010/flags/boot2.flag`.

Or you can try the latest `zip` which may solve brick problem on release page: https://github.com/spacemeowx2/ldn_mitm/releases/download/v1.2.4/ldn_mitm_v1.2.4.zip

**Comment by Xelaalex1234** [comment]
I was actually using the latest version (1.2.4) and atmosphere 0.9.3. I got it sorted now though, I was looking through some config files to see if I had missed something and got some weird errors about corrupted files. So I formatted the sd and reinstalled everything and now it works fine.
