### ISSUE TITLE
Bootloop on Atmosphere 0.9.4 / FW 9.0.0

### ISSUE THREAD

**Issue by detuur** [spacemeowx2/ldn_mitm#22]
ldn_mitm 1.2.4 bootloops on the latest CFW.

**Comment by Cubuss** [comment]
Ldn_mitm is not yet compatible with latest atmosphere/ firmware,

**Comment by Cubuss** [comment]
Please try out the latest ldn-mitm:
https://github.com/spacemeowx2/ldn_mitm/releases/tag/v1.2.6

**Comment by detuur** [comment]
Works flawlessly.
