### ISSUE TITLE
download from appstore .nro

### ISSUE THREAD

**Issue by stuie1** [spacemeowx2/ldn_mitm#23]
0.9.4 atmosphere everytime i download i get version 1.1.1 config idk about the kip i download from the appstore.nro and its the same config nro but i replaced the files right now never been able to work with your lan play its never woprked for me at the dns server but here i go always tells me to updat to 1.1.2 on the config nro

**Comment by Cubuss** [comment]
Please download the latest ldn-mitm from github manually, 
https://github.com/spacemeowx2/ldn_mitm/releases
