### ISSUE TITLE
Animal Crossing drops a communication error as soon as a connection is established

### ISSUE THREAD

**Issue by mid-kid** [spacemeowx2/ldn_mitm#34]
I know it's still early, but I decided to test this game with a couple of people, and I guess this brings me to report this compatibility issue.
The game seems to work, finding the island to connect with works just fine, and you can go through the whole departure animation, until the blue dodo screen, where the system gives a "communication error".
I've captured the ldn_mitm log, though not much seems awry here. https://pastebin.com/raw/KG63Uw9x

**Comment by spacemeowx2** [comment]
the log shows it's probably disconnected from the host, can you host a game and send the log again?

**Comment by mid-kid** [comment]
Here's a log of me hosting: https://pastebin.com/raw/KumKkyBF
The error code is 2618-0006

**Comment by spacemeowx2** [comment]
2618-0006 is an error code from pia library(a networking framework made by N). I guess this game is like super mario party requiring very low latency to avoid people play online. I'll test it later with someone in the same city.

**Comment by spacemeowx2** [comment]
After test, with flag '--pmtu 500' and Switch MTU 1500 the game is playable

**Comment by mid-kid** [comment]
Thanks, will test soon.

**Comment by Darkomen78** [comment]
Hi, I just test ACNH with many settings MTU but I can't get on other's island or get visitor on mine.
Is this a normal launch debug ?
Opening interfaces
[DEBUG]: open \Device\NPF{6D33D277-7017-41B8-9800-FAE73CF5398F} fail: get mac
[DEBUG]: open \Device\NPF{B24CEBCC-A54A-4315-9205-24325039242D} ok
[DEBUG]: open \Device\NPF{8D975325-37E7-477C-92A7-C4C159FD2DE4} fail: get mac
[DEBUG]: open \Device\NPF{8CA26847-E6BF-4CF2-ADA3-4987F6B7E009} fail: get mac
[DEBUG]: open \Device\NPF_Loopback fail: datalink(0)
pcap loop start
[DEBUG]: packet init buffer 000000000056EA00
[DEBUG]: pmtu is set to 500

And when problems comes there is many error like that : uv_pcap_interf_sendpacket failed -1 error

Is there anything I can do on my LAN or firewall ?

**Comment by 0blu** [comment]
After some testing it seems that is just important to set the MTU in the Switch's Wifi settings to `1500`.

I debugged it with Wireshark and saw that Animal Crossing is sending packages with a size lager than `1400` (which is the default).
No need to change the `--pmtu` (which could decrease the performance btw.).
