### ISSUE TITLE
Idn_mitm crashes on Switch ver 10.0.0 with AMS 0.11.0 and above

### ISSUE THREAD

**Issue by bell4631** [spacemeowx2/ldn_mitm#40]
## Expected Behavior

Running Idn_mitm should not cause AMS to crash when booted up onto the console

## Actual Behavior

Error is displayed on the console screen, indicating the following details on the Crash Report:

Atmosphère Crash Report (v1.5):

Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:              ldn.mitm
    Program ID:                  4200000000000010

## Additional Files and Details

[01586994342_4200000000000010.log](https://github.com/spacemeowx2/ldn_mitm/files/4484266/01586994342_4200000000000010.log)

**Comment by spacemeowx2** [comment]
can you try the latest build?  https://github.com/spacemeowx2/ldn_mitm/suites/602213524/artifacts/4475028

**Comment by bell4631** [comment]
The latest build for ldn_mitm is working now on the updated Switch ver 10.0.0 with the AMS support for 0.11.0 and above. Closing this ticket.
