### ISSUE TITLE
ipinfo.cpp not imported anywhere and lan_discovery.cpp calling unimplemented functions in ipinfo.hpp?

### ISSUE THREAD

**Issue by timleg002** [spacemeowx2/ldn_mitm#47]
I also made a PR for deleting ipinfo.cpp source file. The lan_discovery.cpp calls unimplemented functions from the imported header ipinfo.hpp. And the ipinfo.cpp is not imported anywhere

**Comment by spacemeowx2** [comment]
It's compiled and linked in Makefile, no need to import in code

**Comment by timleg002** [comment]
great, thanks.
