### ISSUE TITLE
Pokemon Sword/Shield freezing

### ISSUE THREAD

**Issue by nan-gogh** [spacemeowx2/ldn_mitm#51]
When i have ldn_mitm active my Pokemonster game freezes after loading into the game, followed by a software crash. 

As soon as its deactivated, everything works fine again - must be something about the dlc went online today

**Comment by KutaroKazuki** [comment]
Then keep it of and play in Lan-Mode

**Comment by nan-gogh** [comment]
That is no help and in now way an acceptable solution: I am, using a personal raid bot that needs to connect to the game after startup, which is impossible, when ldn_mitm is off

**Comment by KutaroKazuki** [comment]
> That is no help and in now way an acceptable solution: I am, using a personal raid bot that needs to connect to the game after startup, which is impossible, when ldn_mitm is off

Not really true why I can run Lantern Bot without ldn_mitm? And yes with Lan-Play. I got also sysbot to run months ago without ldn_mitm

**Comment by nan-gogh** [comment]
I have no idea why Lantern Bot is capable of connecting to the game while its in local mode without ldm_mitm - my bot that uses sys-botbase needs that to function. 

I am trying to point out an issue here not to find workarounds or alternatives but to point out that there might be a problem that needs to be fixed with this module i really enjoy

**Comment by KutaroKazuki** [comment]
> I have no idea why Lantern Bot is capable of connecting to the game while its in local mode without ldn_mitm - my bot that uses sys-botbase needs that to function.
> 
> I am trying to point out an issue here not to find workarounds or alternatives but to point out that there might be a problem that needs to be fixed with this module i really enjoy

Lantern also operates with sys-botbase.
I also runnd sysbot.net without any issues.

**Comment by KutaroKazuki** [comment]
Pkhex Live hack same thing I runned that to without any ldn.

**Comment by nan-gogh** [comment]
Awesome. Can someone who is actually interested in finding a solution here that involves fixing ldn please help me identify why the game may be freezing/crashing?

**Comment by drizuid** [comment]
you didn't provide logs or anything useful, so probably not.

**Comment by nan-gogh** [comment]
@drizuid Where can i find logs that are generated, when a game stops functioning and is closed because of that?

**Comment by nan-gogh** [comment]
You know it's just because NX-Shell doesn't show me any report logs when that happens. All i see is a black screen saying, that an error occurred and the software had to be closed. But i'm repeating myself here - i would have uploaded something "useful", if there was something more useful, than what i already told here

**Comment by drizuid** [comment]
ldn_mitm should show up in your hbmenu, click it, enable logs, they are stored in the ldn_mitm folder.

**Comment by Real96** [comment]
To avoid any freezes:
1) strart lnd_mitm
2) wait the console to connect to wifi
3) start the game

The game freezes only when console isn't connected to wifi, so you can easily press home button, wait it to connects and enter again in the game

**Comment by nan-gogh** [comment]
Alright, sorry guys:
I tried what @drizuid told me, which should have been one of the first things i do and there it is again.. The well known error code: 0xf601, 0xf201 - fatal: ldn_mitm is not loaded or too old(requires ldn_mitm >= v1.1.2) press any key to pass out.

Thanks for your help! Thats at least a step in some direction isntead of standing still <3

**Comment by nan-gogh** [comment]
A couple of tests later:

[200773] should_mitm pid: 136 tid: 100abf008968000
[280723] should_mitm pid: 143 tid: 10000000000100d
[11236344] should_mitm pid: 144 tid: 10000000000100d
[11274553] should_mitm pid: 146 tid: 100abf008968000

**Comment by thisismike97** [comment]
This should be fixed with the newest release, can you confirm this? @nan-gogh

**Comment by nan-gogh** [comment]
Works like a charm! No more crashing :D
Thanks a ton to everyone who was involved fixing this - I can finally continue using my bot <3

Awesome work, closing here
