### ISSUE TITLE
Needs update (Pokemon sword and shield crash) (Atmosphere 0.13.0)

### ISSUE THREAD

**Issue by michelrt1992** [spacemeowx2/ldn_mitm#52]
Pokemon Sword and shield crashes with ldn_mitm on Atmosphere 13, needs to be fixed <<

**Comment by KutaroKazuki** [comment]
Will not happen cause Pokémon Sword and Shield still have Lan Mode

**Comment by KutaroKazuki** [comment]
> Pokemon Sword and shield crashes with ldn_mitm on Atmosphere 13, needs to be fixed <<

Will not happen cause Pokémon has a full functioning Lan-Mode

**Comment by Areidz** [comment]
Came to say the same. Even if I didn't connect to any network, it didn't work and it was micro shuttering.
