### ISSUE TITLE
incompatible with Athmosphere 0.14.0

### ISSUE THREAD

**Issue by FaserF** [spacemeowx2/ldn_mitm#57]
Hi, my switch crashes with this module directly after booting with the latest release of athmosphere.

**Comment by Aliasim800** [comment]
Because it needs a update to work with the latest atmosphere, wait for a update for ldn mitm or downgrade your atmosphere version to 0.13.0.

**Comment by drizuid** [comment]
or compile ldn_mitm yourself and ingest the updated libs from atmo14

**Comment by FaserF** [comment]
Fixed with Version 1.5.0
