### ISSUE TITLE
Black screen on the latest Atmosphere 

### ISSUE THREAD

**Issue by MarkoVu12** [spacemeowx2/ldn_mitm#66]
When i first launched, it just says that ldn is too old. After console restart, it's just black screen when i launch ldn. Also, SSBU just loads forever on lan play. Thanks

**Comment by drizuid** [comment]
yes, as the readme.md shows, the latest atmosphere does not work with ldn_mitm...

**Comment by MarkoVu12** [comment]
Oh, ok thanks.. Good to know!
