### ISSUE TITLE
Not working anymore unter Atmos 14.4.4

### ISSUE THREAD

**Issue by wii07** [spacemeowx2/ldn_mitm#67]
Could you make an update? Under 14.4.4 the ldn_mitm modul and the ldnmitm_config.nro are not working anymore. The ldnmitm_config.nro just gives a black screen with no informations anymore about the module.

**Comment by Juaz** [comment]
The README.md specifies that current support only goes up to 14.1 unfortunately.

I tried running it with 14.4 as well, but I can't get past an error soon after unlocking the screen.

**Comment by Juaz** [comment]
The README.md specifies that current support only goes up to 14.1 unfortunately.

I tried running it with 14.4 as well, but I can't get past an error soon after unlocking the screen.

The only options now are either downgrading to 14.2 or waiting for more updates. They are aware.

**Comment by drizuid** [comment]
14.4 (and 15) are supported by ldn 1.6 now.
