### ISSUE TITLE
Error on 0.14.2 & v1.6.0 

### ISSUE THREAD

**Issue by MarkoVu12** [spacemeowx2/ldn_mitm#69]
![20200923_184435_HDR](https://user-images.githubusercontent.com/34967638/94043847-b7ae5500-fdcd-11ea-9da8-b442e1e713ff.jpg)

**Comment by drizuid** [comment]
if you delete boot2.flag from 4200000000000010, does your switch boot normally?

**Comment by drizuid** [comment]
we have multiple confirmations of issues with 14.2 and 14.3. please upgrade to atmosphere 14.4 and use ldn 1.6
