### ISSUE TITLE
Error on Atmos 0.14.3

### ISSUE THREAD

**Issue by stevanocandra** [spacemeowx2/ldn_mitm#70]
[01600949089_4200000000000010.log](https://github.com/spacemeowx2/ldn_mitm/files/5275853/01600949089_4200000000000010.log)

**Comment by drizuid** [comment]
can you add some details? What firmware version? what ldn_mitm version? When you remove the boot2.flag from 4200000000000010 does everything work as normal? is your switch crashing otherwise?

**Comment by stevanocandra** [comment]
I'm using firmware 10.0.0 and Atmos 0.14.3|E
for the idn_mitm using latest version which is 1.6.0.
And I've tried to remove the boot2.flag but still crashed.

**Comment by drizuid** [comment]
if removing the boot2.flag in 4200000000000010 still causes a crash, that is pretty weird, if you fully remove ldn_mitm from the sdcard does it boot normally? Have you tried to upgrade to atmosphere 14.4 and re-test?

**Comment by stevanocandra** [comment]
Hi @drizuid thanks you for solution above. I've upgrade my atmos to 14.4 and it's working like charm...

Thanks...
