### ISSUE TITLE
14.3 atmosphère error

### ISSUE THREAD

**Issue by yanisdreemurr** [spacemeowx2/ldn_mitm#71]
Hi, I come because I have a problem, to put it simply, I am or atmosphere in version 14.3 and my firmware is in 10.2.0, I do not know why but I followed the tutorial from A to Z but it does not work, so if you can help me it would be with great pleasure and sorry for my bad english xD 
[01601068084_4200000000000010.log](https://github.com/spacemeowx2/ldn_mitm/files/5283805/01601068084_4200000000000010.log)

**Comment by drizuid** [comment]
can you confirm what version of ldn_mitm you are using?

**Comment by drizuid** [comment]
we have multiple confirmations of issues with 14.2 and 14.3. please upgrade to atmosphere 14.4 and use ldn 1.6
