### ISSUE TITLE
ldnmitm cfg 1.1.0-ec51fc06 don't work with 1.1.1 kip on Atmosphere

### ISSUE THREAD

**Issue by Skalke** [spacemeowx2/ldn_mitm#8]
### CFW - Atmosphere fusee-1-2 0.8.2 and Atmosphere Kosmos v11.7
![2018123006013400-da63280140b1530cd17755515d814cfe](https://user-images.githubusercontent.com/10077834/50544058-21e69580-0bfa-11e9-98fb-3119a5dd2d4d.jpg)
 
###  v1.0.0-41f0f22d and v1.0.0-434af8c2 is still working..
![2018123006200600-da63280140b1530cd17755515d814cfe](https://user-images.githubusercontent.com/10077834/50544077-25c6e780-0bfb-11e9-813a-297413297b57.jpg)
![2018123006195700-da63280140b1530cd17755515d814cfe](https://user-images.githubusercontent.com/10077834/50544078-28c1d800-0bfb-11e9-9ff6-86529f962944.jpg)

### CFW - ReiNX 2.0.0 - working version is only 1.1.0-ec51fc06

**Comment by spacemeowx2** [comment]
Could you try this? Not sure if it could help because I can't reproduce.

https://github.com/spacemeowx2/ldn_mitm/commit/d68277dee1175d08e4e51d3e68505bc6cb39b5af

[ldn_mitm.zip](https://github.com/spacemeowx2/ldn_mitm/files/2716973/ldn_mitm.zip)

**Comment by kmarsh92** [comment]
even the new files did not work for me as well...getting same problem newest config nro wont load with kips in fusee or hekate environment

**Comment by spacemeowx2** [comment]
Built from https://github.com/spacemeowx2/ldn_mitm/commit/6c172328cbc099772f8c996f45ac601919b8feba [ldn_mitm.zip](https://github.com/spacemeowx2/ldn_mitm/files/2718707/ldn_mitm.zip)

I think it should be fixed

**Comment by Skalke** [comment]
idk but....closing now
